Tg bot
KOTOBOPOT/Queue-Analyzer pull request #26
Opened 2023-05-16 14:58 UTC by EK-Inferno

2023-05-22 21:31 UTC, TimofeyTst requested changes

2023-05-22 21:31 UTC, TimofeyTst commented on lib/tg_bot/include/bot_handlers.h
А то, что везде классы описаны в namespace это обязательно? Стандартный пример из буст библиотеки тоже был с этим, я убрал, потому что не знал зачем вообще это нужно

2023-05-22 21:31 UTC, TimofeyTst commented on lib/tg_bot/include/bot_handlers.h
> +  std::string _help;
Переменные внутри класса объявляем в формате value_, message_, help_

2023-05-22 21:31 UTC, TimofeyTst commented on lib/tg_bot/include/bot_handlers.h
> +class SimpleHandler : public IBotHandler {
Каждый класс лучше объявлять в отдельном файле, тем более тут интерфейсный, от которого будут наследоваться по плану при расширении

2023-05-22 21:31 UTC, TimofeyTst commented on lib/tg_bot/include/bot_handlers.h
> +class CurrentDataHandler : public IBotHandler {
Тоже самое, класссы разделяем

2023-05-22 21:31 UTC, TimofeyTst commented on lib/tg_bot/include/bot_handlers.h
> +class CurrentDataHandler : public IBotHandler {
Надо подумать над названием, CurrentDataHandler как-то непонятно звучит. Что именно как наследник он добавляет?

2023-05-22 21:31 UTC, TimofeyTst commented on lib/tg_bot/include/creator_chouser.h
> +  std::map<std::string, IHandlerCreator::Ptr> _creators;
creators_

2023-05-22 21:31 UTC, TimofeyTst commented on lib/tg_bot/include/handler_creator.h
> +  std::shared_ptr<IDataSource> _database;
database_

2023-05-22 21:31 UTC, TimofeyTst commented on lib/tg_bot/include/handler_creator.h
> +class SimpleCreator : public IHandlerCreator {
Классы раздельно

2023-05-22 21:31 UTC, TimofeyTst commented on lib/tg_bot/include/handler_creator.h
> +class CurrentDataCreator : public IHandlerCreator {
Может тоже название созвучней попробуем? Если получится конечно, я не знаю, что точно он реализует

2023-05-22 21:31 UTC, TimofeyTst commented on lib/tg_bot/include/tg_bot.h
> +class SimpleBot : public ITgBot {
То, что все на интерфейсах - безусловно круто. Осталось только разделить классы по разным файлам)

2023-05-22 21:31 UTC, TimofeyTst commented on lib/tg_bot/include/tg_bot.h
> +  std::vector<TgBot::BotCommand::Ptr> _commands;
Переменные формата var_

2023-05-22 21:31 UTC, TimofeyTst commented on lib/tg_bot/src/bot_handlers.cpp
> +  boost::replace_all(message, "%1", std::to_string(count));
То есть телеграм бот юзает зависимость boost? Без нее никак?

2023-05-22 21:34 UTC, EK-Inferno commented on lib/tg_bot/src/bot_handlers.cpp
> +  boost::replace_all(message, "%1", std::to_string(count));
Без неё сам файл thbot.h не компилится всё равно, но в данной функции убрать можно

2023-05-22 21:37 UTC, EK-Inferno commented on lib/tg_bot/include/bot_handlers.h
Вообще это считается хорошим тоном, как я знаю. А так namespace помогает избежать конфликтов в будущем, ну и при разработке.

2023-05-22 21:43 UTC, EK-Inferno commented on lib/tg_bot/include/bot_handlers.h
> +class SimpleHandler : public IBotHandler {
Проблема в разбитии на несколько файлов в том, что для каждого нового поведения бота придется создавать по 4 новых файла (для креатора заголовочный и реализация, и для самого обработчика)

Интерфейсный стоит выделить, а плодить ещё 10-20 файлов для добавления различного поведения бота не хочется

2023-05-23 08:32 UTC, KOTOBOPOT commented on src/tgbot_main.cpp
> +      QueueBot::SimpleBot("6216802370:AAHtsAHiNSVm4PZv2r1YZHdQu5ap63LF8kE");
В будущем токен должен быть в отдельном конфиге, который будет в гитигнор. Токен не должен хранится в коде в открытом доступе

2023-05-25 12:00 UTC, Inferno-EK commented on lib/tg_bot/include/bot_handlers.h
> +class CurrentDataHandler : public IBotHandler {
Это временное название, как буду нормально бд поключать изменю

2023-05-29 20:36 UTC, TimofeyTst approved these changes
Все круто, мерджим

2023-05-29 20:36 UTC, merged