Computer vision
KOTOBOPOT/Queue-Analyzer pull request #29
Opened 2023-05-22 20:13 UTC by KOTOBOPOT

-Добавил возможность обрабатывания нескольких файлов с видео
-Добавил возможность визуализации
-Добавил db_handler

2023-05-22 20:14 UTC, DaMagus26 approved these changes

2023-05-22 21:07 UTC, TimofeyTst requested changes

2023-05-22 21:07 UTC, TimofeyTst commented on lib/computer_vision/src/frame_visualizer.cpp
> +  // cv::pollKey();
Удалить строку забыл?

2023-05-22 21:07 UTC, TimofeyTst commented on src/main.cpp
> +    SQLiteHandler db_handler("../db/db.db");
db_handler должен быть внутри Video_Processor. Чтобы обращение было в формате video_processor_object.db_handler_.selectInsert....
У меня ведь внутри роутера прокинут db_handler_

2023-05-22 21:11 UTC, TimofeyTst commented on src/main.cpp
> +    SQLiteHandler db_handler("../db/db.db");
Вот в моем роутере создан указатель:
https://github.com/KOTOBOPOT/Queue_Analyser_back/blob/c6fe40a180e4b2035443959b06a8ab03561d4f3e/lib/server/include/router.h#L49

Вот конструктор в роутере, который инициализирует его:
https://github.com/KOTOBOPOT/Queue_Analyser_back/blob/c6fe40a180e4b2035443959b06a8ab03561d4f3e/lib/server/include/router.h#L20

Вот так я его прокидываю в конструктор:
https://github.com/KOTOBOPOT/Queue_Analyser_back/blob/c6fe40a180e4b2035443959b06a8ab03561d4f3e/src/routes.cpp#L16

2023-05-22 21:48 UTC, KOTOBOPOT commented on src/main.cpp
> +    SQLiteHandler db_handler("../db/db.db");
> db_handler должен быть внутри Video_Processor. Чтобы обращение было в формате video_processor_object.db_handler_.selectInsert....
> У меня ведь внутри роутера прокинут db_handler_

Как я понял, либа CV не должна быть связана с базой данных. Все остальные вопросы к Мише

2023-05-23 20:29 UTC, TimofeyTst commented on src/main.cpp
> +    SQLiteHandler db_handler("../db/db.db");
Нужно внести db_handler внутрь video_processor, как я сделал роутер. У нас UML диаграмма так и сделана

2023-05-24 18:49 UTC, TimofeyTst approved these changes

2023-05-24 18:50 UTC, merged