.h instead .hpp
KOTOBOPOT/Queue-Analyzer pull request #3
Opened 2023-04-22 05:10 UTC by TimofeyTst

2023-04-22 05:33 UTC, DaMagus26 requested changes

2023-04-22 05:33 UTC, DaMagus26 commented on src/main.cpp
>  #include "bot.hpp"
А тут што не поменял?

2023-04-22 05:33 UTC, DaMagus26 commented on src/main.cpp
>  #include "model.hpp"
Соответственно и тут

2023-04-22 06:03 UTC, TimofeyTst commented on src/main.cpp
>  #include "bot.hpp"
Ну это чтобы с вашими файлами конфликта не возникло, подозреваю что вы меняли их, и скорее всего удалили файлы с такими названиями варинципе

2023-04-22 08:26 UTC, KOTOBOPOT requested changes

2023-04-22 08:26 UTC, KOTOBOPOT commented on lib/server/include/handle_request.h
> -#include "error.hpp"
Согласно пункту 4 из вики: "Порядок включения заголовков: сначала include'ятся локальные файлы (те, что в кавычках), потом файлы стандартной библиотеки, потом файлы сторонних библиотек"

2023-04-22 21:09 UTC, KOTOBOPOT approved these changes

2023-04-24 09:27 UTC, DaMagus26 approved these changes

2023-04-24 13:41 UTC, merged